---

env:
  browser: true
  es2020: true

parser: babel-eslint

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  allowImportExportEverywhere: false,
  codeFrame: true

rules:
  linebreak-style: off
  no-console: off
  no-underscore-dangle: off
  strict: 0

